eunomia:
  operator:
    namespace: "eunomia-operator"
    deployment:
      enabled: true
      nsRbacOnly: false
      clusterViewer: true
      operatorHub: false
    replicas: 1
    serviceAccount: "eunomia-operator"

    image:
      repository: "quay.io"
      name: "kohlstechnology/eunomia-operator"
      tag: "latest"
      pullPolicy: Always

    ingress:
      enabled: false
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: hello-eunomia.info
          paths:
            - path: /
              portName: webhook
            - path: /metrics
              portName: metrics

      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    service:
      # Enable the below setting to expose the service through a cloud load balancer
      annotations: {}
        # cloud.google.com/load-balancer-type: "Internal"
        # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      #type: LoadBalancer

    nodeSelector: {}

    tolerations: []

    affinity: {}

    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi

    podSecurityPolicy:
      # Specifies whether PodSecurityPolicy should be created.
      enabled: false

    openshift:
      enabled: false
      route:
        enabled: false
