apiVersion: v1
kind: Service
metadata:
  name: eunomia-operator
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    name: eunomia-operator
  ports:
  - name: webhook
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
