teamName: "team1"
namespaces: 
  - name: team1-ns1
    parameterPath: examples/cluster/teams/team1/app1/parameters
    templatePath: examples/hello-world-helm/templates
  - name: team1-ns2
    parameterPath: examples/cluster/teams/team1/app2/parameters
    templatePath: examples/hello-world-helm/templates
  - name: team1-ns3
    parameterPath: examples/cluster/teams/team1/app3/parameters
    templatePath: examples/hello-world-helm/templates
GitOpsConfig:
  serviceAccountRef: "eunomia-runner"
  templateProcessorImage: "quay.io/kohlstechnology/eunomia-helm:v0.0.1"
  triggers:
    cron: "* */8 * * *"
  templateSource:
    uri: "https://github.com/Smiley73/eunomia"
    ref: "clusterdemo"
  parameterSource:
    uri: "https://github.com/Smiley73/eunomia"
    ref: "clusterdemo"
