{{- with .Values.eunomia.operator }}
{{- if .deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eunomia-operator
  namespace: {{ .namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      name: eunomia-operator
  template:
    metadata:
      labels:
        name: eunomia-operator
    spec:
      serviceAccountName: {{ .serviceAccount }}
      containers:
        - name: eunomia-operator
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command:
          - eunomia-operator
          env:
            - name: JOB_TEMPLATE
              value: /templates/job.yaml
            - name: CRONJOB_TEMPLATE
              value: /templates/cronjob.yaml
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "eunomia-operator"
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
